1.Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
try:
    n = 5/0
except Exception as e:
    print(e)
finally:
    print("----Write this exception to log file!---")


division by zero
----Write this exception to log file!---


2. Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [25]:
sub = ["Americans", "Indians"]
verb = ["Play", "watch"]
obj = ["Baseball","cricket"]
for i in [i+' '+j+' '+k for i in sub for j in verb for k in obj]:
    print(i)


Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


Task 2: 1. Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [36]:
import numpy as np
def fnVandermonde(l):
    array_list = [[i**j for i in l] for j in range(len(l)-1, -1, -1)] 
    return(np.array(array_list).transpose())

if __name__ == '__main__':
    lst = list(map(int,input("Enter list items separated by commas").strip().split(",")))
    print(fnVandermonde(lst))

Enter list items separated by commas1,2,3,5
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
